name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: employee_directory
          MYSQL_USER: springstudent
          MYSQL_PASSWORD: SpringStudent
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          until mysql -h 127.0.0.1 -P 3306 -u springstudent -pSpringStudent -e "SELECT 1"; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Unit Tests
        run: mvn test --file spring-mvc-security-employee/spring-mvc-security/pom.xml

      - name: Build the Application
        working-directory: spring-mvc-security-employee/spring-mvc-security
        run: mvn clean package

      - name: Verify JAR file
        run: ls -l spring-mvc-security-employee/spring-mvc-security/target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./spring-mvc-security-employee/spring-mvc-security
          file: ./spring-mvc-security-employee/spring-mvc-security/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-mvc-security:latest
