name: Build & Deploy Spring app
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Unit Tests
        run: mvn -B test --file spring-mvc-security-employee/spring-mvc-security/pom.xml

      - name: Build the application
        run: |
          mvn clean 
          mvn -B package --file spring-mvc-security-employee/spring-mvc-security/pom.xml
